### ISSUE TITLE
differences in rendering between $this->form and $this->formRow

### ISSUE THREAD

**Issue by bogal** [neilime/zf2-twb-bundle#100]
When i render my form using the simple and concise:
echo $this->form($this->editForm);
... it is rendered lovely.

However if i need to add other markup elements that are not placed in the form object, i am forced to use $this->formRow($this->editForm->get('element'));

Even though both have the same form object properties, they are rendered in different ways. Using $this->formRow and the form is all over the place, even when using column-size properties.

Take the following markup for an element in my form class as an example:
	$this->add(array(
            'name' => 'name',
            'options' => array(
                'label' => 'Name:',
            	'column-size' => 'sm-5',
    			'label_attributes' => array(
    				'class' => 'control-label col-sm-2'
            	)
            ),
            'attributes' => array(
                'required' => true
            ),
            'type' => 'Text'
        ));

To compare the difference in markup of this element:
-using echo $this->form($form);
< div class="form-group ">
  < label class="control-label col-sm-2">Name:< / label>
  < div class=" col-sm-5">
    < input type="text" value="" class="form-control" required="required" name="user[name]">
  < / div>
< / div>

-using echo $this->formRow($form->get('name'));
< div class="form-group  col-sm-5">
  < label class="control-label col-sm-2">Name:< / label>
  < input type="text" value="" class="form-control" required="required" name="user[name]">
< / div>

...which results in a very different appearance. The first method displays everything perfectly. The second method has everything all over the place. 

Shouldn't they be rendered the same? Or am i not using the view helpers correctly?

**Comment by berturion** [comment]
+1 @Estigy that sounds good.
I have a question, is it possible to assagn 'twb-layout' option when calling $this->formRow('my-field') ?
Like:

    $this->formRow('my-field')->setOptions(array('twb-layout' => \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL))

**Comment by Saeven** [comment]
I'm facing the same behavior.  This output looks right (twig):

```twig
{{ form( theform ) }}
```

but this output does not:

```twig
{% for f in server_form %}
    {{ formRow( f ) }}
{% endfor %}
```

I would also like to keep layout and object domain separated, for now, this works.  In the layout file:

```twig
{% for f in server_form %}
    {% do f.setOption( 'twb-layout', 'horizontal' ) %}
    {{ formRow( f ) }}
{% endfor %}
```
