### ISSUE TITLE
Format Zend DateTimeSelect

### ISSUE THREAD

**Issue by rplumlee** [neilime/zf2-twb-bundle#113]
Hey, I'm having trouble formatting my zend date and time dropdowns.  Here's an example form element:

         $this->add(array(
             'name' => 'firm_response_date',
             'type' => 'Zend\Form\Element\DateTimeSelect',
             'options' => array(
                 'label' => 'Approve Date',
                 'column-size' => 'md-14',
                )
         ));                   

I want it to be formatted into TwB dropdown buttons, which call for 
 $oButton = new \Zend\Form\Element\Button
             ('default',array(
                         'label' => 'Default',
                         'dropdown' => $aDropDownOptions));

I'm fairly new at this, but I don't understand how to match up the formatting. for the rest of my forms I was able to implement the twbbundle by just modifying the options and attributes, but I'm having trouble here. any help would be greatly appreciated.

Cheers,
Reid

**Comment by neilime** [comment]
I'm affraid that Bootstrap does not provide a way to insert a input in a dropdown list. Can you share an exemple (html) of what you want to do.
