### ISSUE TITLE
Inline elements in horizontal form

### ISSUE THREAD

**Issue by Alfredao** [neilime/zf2-twb-bundle#116]
I have a question for you.

Is possible to render inline elements in horizontal form? I searched at the docs and look at the code but I didn't find it.
I want something like this. 

My actual form:

![form](https://cloud.githubusercontent.com/assets/815781/5361997/b5aff858-7fb6-11e4-8649-429885e42560.PNG)

I want to put the buttons inline like this:

![new_form](https://cloud.githubusercontent.com/assets/815781/5362025/dcfc0f96-7fb6-11e4-9ca3-47d01228db3e.PNG)

Thank you all!

**Comment by malinink** [comment]
You could create Fieldset with two buttons, and add it into your form with option 
'twb-layout' => \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE

More information about Fieldsets here:
http://framework.zend.com/manual/current/en/modules/zend.form.collections.html
