### ISSUE TITLE
Allow help-block field param to contain HTML

### ISSUE THREAD

**Issue by matthewfedak** [neilime/zf2-twb-bundle#118]
I am working on a site which needs a Terms and Conditions checkbox that has a couple of sentences containing hyperlinks and bold font formatting. This could be done by having a multi-sentence field label and disabling html escaping but I would prefer to have a short label and a lengthy html help-block instead.

For example:

I agree to the T&C's (the field label)

(then underneath I would like a rich text help block)

Through <em>signing up</em> you are <strong>agreeing</strong> to our <a href="/terms-and-conditions" target="_blank">Terms &amp; Conditions</a> and <a href="/privacy-policy" target="_blank">Privacy Policy</a>. You also agree to receive information by post, telephone, email &amp; SMS from ourselves and our third party sponsors. 

I personally think this is better than having a very long rich text label.

**Comment by neilime** [comment]
Hi,

Sorry for the delay, the version la version allows using html into help block (the content is escaped only if it does not contain html tags)

**Comment by matthewfedak** [comment]
Cool great work. Thanks!
