### ISSUE TITLE
How to use zf2-twb-bundle with standalone Zend forms?

### ISSUE THREAD

**Issue by karailiev** [neilime/zf2-twb-bundle#119]
Hi all,
I'm working on an application that is not using the full Zend Framework.
I'm only relying on pieces of it, mainly the forms.
My original code looks like this (thanks to Carl McDade's [for his article](http://cvlive.blogspot.com/2014/02/how-to-use-zend-framework-2-forms-in_14.html):
```php
$formView = new \Zend\View\Renderer\PhpRenderer();
$zfc = new \Zend\Form\View\HelperConfig();
$zfc->configureServiceManager($formView->getHelperPluginManager());

echo $formView->form()->openTag($form);
echo $formView->formCollection($form);
echo $formView->form()->closeTag($form);
```

So, as I'm not using the the full Zend Framework, I struggled a bit with how to integrate the zf2-twb-bundle. After looking into the code and some reverse engineering here is what I came with.

First, I extended the `Zend\Form\View\HelperConfig()` class:
```php
class QuipuHelperConfig extends Zend\Form\View\HelperConfig {
       function __construct() {
             $twb = new TwbBundle\Module();
             foreach ($twb->getConfig()['view_helpers']['invokables'] as $key => $val) {
                    $this->invokables[$key] = $val;
             }
       }
}
```

Then, I modified the code in the template as follows:
```php
$formView = new \Zend\View\Renderer\PhpRenderer();
$zfc = new QuipuHelperConfig();
$zfc->configureServiceManager($formView->getHelperPluginManager());
 
$twbForm = new TwbBundleForm();
$twbForm ->setView($formView);
echo $twbForm ($form, null);
```

This seems to work fine now, but as I'm new to ZF2, I wanted to check if this is really the best (or even valid) way to integrate the library.

I would appreciate all your feedback.

Regards,
Valentin

**Comment by neilime** [comment]
Hi,

Sorry for this late reply. 
I think that your solution is fine.
