### ISSUE TITLE
openTag - TwbBundleForm

### ISSUE THREAD

**Issue by N3XT0R** [neilime/zf2-twb-bundle#123]
Hello,
i don't have a bug, only a feedback to the openTag Method from TwbBundleForm (Namespace: TwbBundle\Form\View\Helper).

SetFormClass is a protected function. 
openTag gets the attribute $formlayout.

It is not possible to set an own class for forms generated by openTag.

A better way would be to rewrite the openTag Method to:

```
/**
     * Generate an opening form tag
     *
     * @param  null|\Zend\Form\FormInterface $form
     * @param string $sFormLayout
     * @return string
     */
    public function openTag(\Zend\Form\FormInterface $form = null, $sFormLayout = self::LAYOUT_HORIZONTAL)
    {
        $this->setFormClass($form, $sFormLayout);
        return parent::openTag($form);
    }
```

instead of 

```
public function openTag(\Zend\Form\FormInterface $form = null)
    {
        $this->setFormClass($form, $this->formLayout);
        return parent::openTag($form);
    }
```

**Comment by neilime** [comment]
As written in the README file, you can set the layout as following : 

Open form tag with a specific layout :
```php
$this->form(null,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE)->openTag($oForm);
```

**Comment by srayner** [comment]
Maybe mine is a separate issue, but I can't get openTag() to render a <form> element, it always renders a <fieldset> element.
