### ISSUE TITLE
Coexistence of ZF2 and TwbBundle view helpers

### ISSUE THREAD

**Issue by xelax90** [neilime/zf2-twb-bundle#127]
I have a project where I have a back-end, where I want to use bootstrap and a front-end where I need custom output and want to use the default ZF2 view helpers. 
For this I have created a small [module](https://github.com/xelax90/xelax-twb-unmask) which essentially maps all TwbBundle helpers which overwrite default functionality from formFoo to twbFormFoo. Maybe you should provide this functionality as an option in your module, which is not very hard if you check out my small extensions to your view helpers. I can give you some pull requests if I find time but I cant promise, this will be soon.

**Comment by edigu** [comment]
Hey @xelax90 simply remove `TwbBundle` module from your `modules` stack based on request in` `application.config.php`. This is most simple solution. Check an environment variable (or `$_SERVER['SERVER_NAME']`) index.php and conditionally load required modules based on request.

**Comment by xelax90** [comment]
Yes, this could be a solution in some cases, but i want to use the `TwbBundle` on some routes and don't want it on some others. So what I would need is to access the route match, which is obviously loaded after the configuration.

**Comment by Estigy** [comment]
@xelax90 This is not how the ZF2 module system works...
