### ISSUE TITLE
ZF 2.4.* compatibility

### ISSUE THREAD

**Issue by edigu** [neilime/zf2-twb-bundle#135]
Yesterday, [ZF 2.4.0 released](http://framework.zend.com/blog/zend-framework-2-4-0-released.html) and when i try to install together with Zf2TwbBundle, composer generates the message below:

```
neilime/zf2-twb-bundle dev-master requires zendframework/zend-view 2.3.* -> 
satisfiable by zendframework/zendframework[2.3.7], 
zendframework/zend-view[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7].
```

Is it possible to update composer.json dependencies without breaking any existing functionality?

Since last release introduces sort of BC breaks, here is the list of `Zend\Form` related changes to check, I am not sure whether one will cause problems:

 - zendframework/zf2#6271 Ensures all Form view helpers allow the full spectrum of HTML5 attributes.
 - zendframework/zf2#6656 Adds a getElements() method to each of DateSelect and MonthSelect to return a list of each composed Select element (as each composes multiple elements).
 - zendframework/zf2#6754 Adds a new preserveDefinedOrder flag for Zend\Form\Annotation\AnnotationBuilder; if true, elements will be created and listed in the order in which they were defined in the class parsed. #7276 adds support for the preserve_defined_order configuration flag to the FormAnnotationBuilderFactory.
 - zendframework/zf2#6783 Adds @ContinueIfEmpty as an available form annotation.
 - zendframework/zf2#7171 modifies Zend\Form\Form::prepare() to reset (i.e., clear) password values, ensuring they are not displayed in rendered forms.
 - zendframework/zf2#7181 updates Zend\Form\View\Helper\FormButton to translate the button content.

**Comment by Martin-P** [comment]
I noticed the reference to https://github.com/zendframework/zf2/pull/7171

> https://github.com/zendframework/zf2/pull/7171 modifies Zend\Form\Form::prepare() to reset (i.e., clear) password values, ensuring they are not displayed in rendered forms.

I updated the title, because it does not modify `Zend\Form\Form::prepare()` (which was my initial approach), but only removes the password value in the `render()` method of the view helper.

**Comment by seyfer** [comment]
https://github.com/neilime/zf2-twb-bundle/issues/139

**Comment by ThaDafinser** [comment]
@edigu should be fine now?

**Comment by edigu** [comment]
Sorry for the late response. it seems like fine
