### ISSUE TITLE
Declaration of TwbBundleFormRow::render() should be compatible with FormRow::render()

### ISSUE THREAD

**Issue by CreativeNative** [neilime/zf2-twb-bundle#136]
I got this strict error with the versions:
* zendframework/zendframework (2.4.0)
* neilime/zf2-twb-bundle (2.2.0)

Declaration of TwbBundle\Form\View\Helper\TwbBundleFormRow::render() should be compatible with Zend\Form\View\Helper\FormRow::render(Zend\Form\ElementInterface $element, $labelPosition = NULL)

zendframework/zendframework (2.4.0)
neilime/zf2-twb-bundle (2.2.0)

If I install your version 2.3.0, the error is gone, but there is still this bug with composer  "zendframework/zendframework": "2.3.*@stable"

https://github.com/neilime/zf2-twb-bundle/issues/135

Could you please tag a new version.

**Comment by StyleT** [comment]
I have the same issue :(

**Comment by Saeven** [comment]
I'm not having these issues at all, you guys try getting onto dev-master?

"neilime/zf2-twb-bundle": "dev-master",

**Comment by StyleT** [comment]
I have `"neilime/zf2-twb-bundle": "2.*@stable"` in Composer. Is it safe to write "dev-master"?

**Comment by Saeven** [comment]
```
"minimum-stability": "dev",
"require" : {
...
"neilime/zf2-twb-bundle": "dev-master",
...
```

**Comment by CreativeNative** [comment]
@StyleT Normaly not, because dev-master is the actually development branch. Because of this I asked for a stable tag.

**Comment by Saeven** [comment]
Yea but we gotta be fair to neillime!  ZF 2.4 is really brand new.  If you're willing to run a 1-2 day old framework, a dev-master tag on a form decorator shouldn't really be scaring you ;)

**Comment by neilime** [comment]
Version 2.4.0 is here.

**Comment by CreativeNative** [comment]
Works like a charm. Awesome! Thanks a lot.
