### ISSUE TITLE
View\Helper\TwbBundleFormButton::render the second param $sButtonContent is null

### ISSUE THREAD

**Issue by SpencerZ** [neilime/zf2-twb-bundle#138]
/Zend/Form/View/Helper/FormInput:: __invoke() only has one param: ElementInterface $element
but /Zend/Form/View/Helper/FormButton::__invoke() has two params, besides the $element, the other param is $buttonContent

![image](https://cloud.githubusercontent.com/assets/8024424/7082336/e44e6f72-df84-11e4-8385-77d7b935750d.png)

I tried to output the $helper($element), found the button render helper result is null

**Comment by seyfer** [comment]
:+1: same error for me

**Comment by SpencerZ** [comment]
@seyfer 
I found the mistake
 the $form->add(array()) format is wrong
the example format you can see this http://neilime.github.io/zf2-twb-bundle/demo.html
