### ISSUE TITLE
While attempting to create formelement(alias: form_element) an invalid factory was registered for this instance type.

### ISSUE THREAD

**Issue by YuriStruszczynski** [neilime/zf2-twb-bundle#146]
Hi,

i got the following error for every form i want to show:

While attempting to create formelement(alias: form_element) an invalid factory was registered for this instance type.

I use the ZF2 2.4 and twb_bundle 2.4.0 last realeas.

#0 /www/htdocs/w0129f60/ZendFramework/library/Zend/ServiceManager/ServiceManager.php(638): Zend\ServiceManager\AbstractPluginManager->createFromFactory('formelement', 'form_element')
#1 /www/htdocs/w0129f60/ZendFramework/library/Zend/ServiceManager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('form_element', 'formelement')
#2 /www/htdocs/w0129f60/ZendFramework/library/Zend/ServiceManager/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#3 /www/htdocs/w0129f60/ZendFramework/library/Zend/ServiceManager/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('form_element', true)
#4 /www/htdocs/w0129f60/ZendFramework/library/Zend/View/Renderer/PhpRenderer.php(372): Zend\ServiceManager\AbstractPluginManager->get('form_element', NULL)
#5 /www/htdocs/w0129f60/ZendFramework/library/Zend/Form/View/Helper/FormRow.php(411): Zend\View\Renderer\PhpRenderer->plugin('form_element')
#6 /www/htdocs/w0129f60/ZendFramework/library/Zend/Form/View/Helper/FormRow.php(122): Zend\Form\View\Helper\FormRow->getElementHelper()
#7 /www/htdocs/w0129f60/crm/vendor/TwbBundle/src/TwbBundle/Form/View/Helper/TwbBundleFormRow.php(56): Zend\Form\View\Helper\FormRow->render(Object(Zend\Form\Element\Hidden))
#8 /www/htdocs/w0129f60/ZendFramework/library/Zend/Form/View/Helper/FormRow.php(107): TwbBundle\Form\View\Helper\TwbBundleFormRow->render(Object(Zend\Form\Element\Hidden), 'prepend')
#9 [internal function]: Zend\Form\View\Helper\FormRow->__invoke(Object(Zend\Form\Element\Hidden))
#10 /www/htdocs/w0129f60/ZendFramework/library/Zend/View/Renderer/PhpRenderer.php(393): call_user_func_array(Object(TwbBundle\Form\View\Helper\TwbBundleFormRow), Array)
#11 /www/htdocs/w0129f60/crm/vendor/TwbBundle/src/TwbBundle/Form/View/Helper/TwbBundleForm.php(74): Zend\View\Renderer\PhpRenderer->__call('formRow', Array)
#12 /www/htdocs/w0129f60/crm/vendor/TwbBundle/src/TwbBundle/Form/View/Helper/TwbBundleForm.php(74): Zend\View\Renderer\PhpRenderer->formRow(Object(Zend\Form\Element\Hidden))
#13 /www/htdocs/w0129f60/crm/vendor/TwbBundle/src/TwbBundle/Form/View/Helper/TwbBundleForm.php(34): TwbBundle\Form\View\Helper\TwbBundleForm->render(Object(Crm\Form\ShootingForm), 'horizontal')
#14 [internal function]: TwbBundle\Form\View\Helper\TwbBundleForm->__invoke(Object(Crm\Form\ShootingForm))
#15 /www/htdocs/w0129f60/ZendFramework/library/Zend/View/Renderer/PhpRenderer.php(393): call_user_func_array(Object(TwbBundle\Form\View\Helper\TwbBundleForm), Array)
#16 /www/htdocs/w0129f60/crm/module/Crm/view/crm/shooting/edit.phtml(18): Zend\View\Renderer\PhpRenderer->__call('form', Array)
#17 /www/htdocs/w0129f60/crm/module/Crm/view/crm/shooting/edit.phtml(18): Zend\View\Renderer\PhpRenderer->form(Object(Crm\Form\ShootingForm))
#18 /www/htdocs/w0129f60/ZendFramework/library/Zend/View/Renderer/PhpRenderer.php(501): include('/www/htdocs/w01...')
#19 /www/htdocs/w0129f60/ZendFramework/library/Zend/View/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#20 /www/htdocs/w0129f60/ZendFramework/library/Zend/View/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#21 /www/htdocs/w0129f60/ZendFramework/library/Zend/View/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#22 /www/htdocs/w0129f60/ZendFramework/library/Zend/Mvc/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#23 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#24 /www/htdocs/w0129f60/ZendFramework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#25 /www/htdocs/w0129f60/ZendFramework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#26 /www/htdocs/w0129f60/ZendFramework/library/Zend/Mvc/Application.php(353): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#27 /www/htdocs/w0129f60/ZendFramework/library/Zend/Mvc/Application.php(328): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#28 /www/htdocs/w0129f60/crm/public/index.php(17): Zend\Mvc\Application->run()
#29 {main}

Any ideas from you guys?

Kind regards, Yuri

**Comment by MaracujaJoe** [comment]
When i outcomment line 220: //$sElementContent = $this->getElementHelper()->render($oElement); in TwbBundleFormRow.php

and print out print_r($oElement); i get this form and the site works again:

<form id="project" class="form-inline" action="/customers/" enctype="multipart/form-data" name="project" method="POST">
Zend\Form\Element Object
(
    [attributes:protected] =&gt; Array
        (
            [name] =&gt; name
            [type] =&gt; text
            [placeholder] =&gt; Name
        )

    [label:protected] =&gt; 
    [labelAttributes:protected] =&gt; Array
        (
            [class] =&gt; col-sm-2
        )

    [labelOptions:protected] =&gt; Array
        (
        )

    [messages:protected] =&gt; Array
        (
        )

    [options:protected] =&gt; Array
        (
            [label] =&gt; 
            [column-size] =&gt; 
            [label_attributes] =&gt; Array
                (
                    [class] =&gt; col-sm-2
                )

        )

    [value:protected] =&gt; 
)
<div class="form-group "></div>
Zend\Form\Element Object
(
    [attributes:protected] =&gt; Array
        (
            [name] =&gt; prename
            [type] =&gt; text
            [placeholder] =&gt; Vorname
        )

    [label:protected] =&gt; 
    [labelAttributes:protected] =&gt; Array
        (
            [class] =&gt; col-sm-2
        )

    [labelOptions:protected] =&gt; Array
        (
        )

    [messages:protected] =&gt; Array
        (
        )

    [options:protected] =&gt; Array
        (
            [label] =&gt; 
            [column-size] =&gt; 
            [label_attributes] =&gt; Array
                (
                    [class] =&gt; col-sm-2
                )

        )

    [value:protected] =&gt; 
)
<div class="form-group "></div>
Zend\Form\Element Object
(
    [attributes:protected] =&gt; Array
        (
            [name] =&gt; customer_id
            [type] =&gt; text
            [placeholder] =&gt; Kunden-Nummer
        )

    [label:protected] =&gt; 
    [labelAttributes:protected] =&gt; Array
        (
            [class] =&gt; col-sm-2
        )

    [labelOptions:protected] =&gt; Array
        (
        )

    [messages:protected] =&gt; Array
        (
        )

    [options:protected] =&gt; Array
        (
            [label] =&gt; 
            [column-size] =&gt; 
            [label_attributes] =&gt; Array
                (
                    [class] =&gt; col-sm-2
                )

        )

    [value:protected] =&gt; 
)
<div class="form-group "></div>
<a href="/customers/" class="btn btn-pipe"><span class="glyphicon glyphicon-remove"></span></a>
Zend\Form\Element\Button Object
(
    [attributes:protected] =&gt; Array
        (
            [type] =&gt; submit
            [name] =&gt; submit
            [class] =&gt; btn-pipe
        )

    [label:protected] =&gt; Suchen
    [labelAttributes:protected] =&gt; Array
        (
        )

    [labelOptions:protected] =&gt; Array
        (
        )

    [messages:protected] =&gt; Array
        (
        )

    [options:protected] =&gt; Array
        (
            [label] =&gt; Suchen
            [column-size] =&gt; 
        )

    [value:protected] =&gt; 
)
<div class="form-group "></div>

</form>

**Comment by neilime** [comment]
Sorry for this late reply, have you find a solution for your problem ? Maybe you can try to use the last version available
