### ISSUE TITLE
Overriding opening tag class not possible?

### ISSUE THREAD

**Issue by utrenkner** [neilime/zf2-twb-bundle#159]
Maybe this is a misunderstanding of how this bundle should work, but I can't get Bootstraps standard vertical form layout.

If I try:
$form->setAttribute('class', 'form-vertical row-border');
It *adds* in the opening tag these two classes to  twb-bundle's default "form-horizontal".

But I want to completely  replace the default "form-horizontal". Is this not possible?

**Comment by neilime** [comment]
You have to render your form with null layout
```php
$this->render($form,null);
```
