### ISSUE TITLE
can you update the demo site to document inline-checkbox

### ISSUE THREAD

**Issue by srayner** [neilime/zf2-twb-bundle#160]
There is an option for inline on the multicheckbox view helper but it's not documented on the demo site?

**Comment by neilime** [comment]
The demo site shows how to deals with inline multicheckbox : http://neilime.github.io/zf2-twb-bundle/demo.html#supported-form

**Comment by srayner** [comment]
Sorry, my original comment was not clear enough. It's been a while since I looked at this but I think the demo code is incorrect. You have to specify 'class' => 'inline-checkbox', your demo code does not include this.

**Comment by neilime** [comment]
When you set the option `inline` to `true`, the class `checkbox-inline` (or `radio-inline` for radio buttons)  is automatically set by the helper
