### ISSUE TITLE
[Question] <br/> after each .form-group 

### ISSUE THREAD

**Issue by someother1** [neilime/zf2-twb-bundle#167]
```
Zend 2 - 2.*
TwbBundle: 2.*@stable
```

I dont really know if this is related to this bundle..

If i render my form via `<?=$this->form($oForm, null);?>` after each element zend is placing a `<br/>` tag, which expands the form in the height.
I do not see this `<br/>` tags in your example so i guess you have removed them somewhere.

How and where did you do this?

Kindly regards

**Comment by neilime** [comment]
I have looking for `<br/>` every where in this project en Zend\Form project, I don't see any occurrence of it.
Maybe you have something in your script which transforms end of line characters into `<br/>`, like `nl2br` function or something like this.

**Comment by someother1** [comment]
Finaly saw that the ```<br/>```  comes from the [Bootstrapdialog](https://github.com/nakupanda/bootstrap3-dialog) project.
Sorry for juggling with your time here..
