### ISSUE TITLE
Usage in standalone views

### ISSUE THREAD

**Issue by bogal** [neilime/zf2-twb-bundle#168]
I have previously used this component in ZF2 MVC apps. I am now working on a project that uses zend-view as a standalone component, and i was wondering if it was still possible to use this module to render forms (since it has to be added to modules[], which this project does not have).

**Comment by neilime** [comment]
Maybe this issue can helps you : https://github.com/neilime/zf2-twb-bundle/issues/119

**Comment by bogal** [comment]
Thanks for the link. I had a read and tried using the code but don't seem to be getting the same results. Mine is choking on the creation of TwbBundle\Module, i suspect because the code points to a couple of paths that may not exist on my site - however also editing this file to return empty arrays (in both getConfig and getAutoloaderConfig) didn't make any difference.

**Comment by neilime** [comment]
can you post a gist with a sample of your implementation
