### ISSUE TITLE
While attempting to create formelement(alias: form_element) an invalid factory was registered for this instance type.

### ISSUE THREAD

**Issue by igorkrup** [neilime/zf2-twb-bundle#172]
Same issue was reported ([#146](https://github.com/neilime/zf2-twb-bundle/issues/146)) but it was closed without solution.

`Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotCreatedException' with message 'While attempting to create formelement(alias: form_element) an invalid factory was registered for this instance type.' in /zend/library/Zend/ServiceManager/AbstractPluginManager.php:209 Stack trace: #0 /zend/library/Zend/ServiceManager/ServiceManager.php(612): Zend\ServiceManager\AbstractPluginManager->createFromFactory('formelement', 'form_element') #1 /zend/library/Zend/ServiceManager/ServiceManager.php(572): Zend\ServiceManager\ServiceManager->doCreate('form_element', 'formelement') #2 /zend/library/Zend/ServiceManager/ServiceManager.php(504): Zend\ServiceManager\ServiceManager->create(Array) #3 /zend/library/Zend/ServiceManager/AbstractPluginManager.php(103): Zend\ServiceManager\ServiceManager->get('form_element', true) #4 /zend/library/Zend/View/Renderer/PhpRenderer.php(37 in /zend/library/Zend/ServiceManager/AbstractPluginManager.php on line 209`

**Comment by neilime** [comment]
Which version of zf2 and zf2-twb-bundle are you using ?

**Comment by igorkrup** [comment]
ZF 2.4.9 and TwBundle 2.6.0

**Comment by neilime** [comment]
Please can you post the entire stacktrace of the error to understand this issue

**Comment by igorkrup** [comment]
`
Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotCreatedException' with message 'While attempting to create formelement(alias: form_element) an invalid factory was registered for this instance type.' in /zend/library/Zend/ServiceManager/AbstractPluginManager.php:246 Stack trace: #0 /zend/library/Zend/ServiceManager/ServiceManager.php(638): Zend\ServiceManager\AbstractPluginManager->createFromFactory('formelement', 'form_element') #1 /zend/library/Zend/ServiceManager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('form_element', 'formelement') #2 /zend/library/Zend/ServiceManager/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array) #3 /zend/library/Zend/ServiceManager/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('form_element', true) #4 /zend/library/Zend/View/Renderer/PhpRenderer.php(37 in /zend/library/Zend/ServiceManager/AbstractPluginManager.php on line 246`

**Comment by neilime** [comment]
Hum, If you're using ZF2 the last trace should be index.php. I can't help you to debug if I can't have a look at the full stack trace.
