### ISSUE TITLE
badge for string "0" 

### ISSUE THREAD

**Issue by jroedel** [neilime/zf2-twb-bundle#177]
It seems the badge view helper doesn't allow the argument string "0".  I verified the type with var_dump and got the following message:

string '0' (length=1)
( ! ) Catchable fatal error: Object of class TwbBundle\View\Helper\TwbBundleBadge could not be converted to string in ...

The problem code is this:
```
    public function __invoke($sBadgeMessage = null, array $aBadgeAttributes = null)
    {
        if (!$sBadgeMessage) {
            return $this;
        }
        return $this->render($sBadgeMessage, $aBadgeAttributes);
    }
```
Consider changing ```if (!$sBadgeMessage) ``` to ```if (is_null($sBadgeMessage))```.

Thanks!

**Comment by neilime** [comment]
You can try with the very last version, it has been fixed. Thank you
