### ISSUE TITLE
Change self to static to allow to easily override format patterns in subclasses

### ISSUE THREAD

**Issue by netbrothers-tr** [neilime/zf2-twb-bundle#191]
Some (or all?) format patterns like [this one](https://github.com/neilime/zf2-twb-bundle/blob/7bfa5ad7bf44ad1d0ffc782fb56c760b7b16e6b9/src/TwbBundle/Form/View/Helper/TwbBundleFormRow.php#L23)

    protected static $horizontalLayoutFormat = '<div class="%s">%s</div>';

are accessed within their class via `self` as in [this line](https://github.com/neilime/zf2-twb-bundle/blob/7bfa5ad7bf44ad1d0ffc782fb56c760b7b16e6b9/src/TwbBundle/Form/View/Helper/TwbBundleFormRow.php#L310) for example. However, because of [late static binding](http://php.net/manual/en/language.oop5.late-static-bindings.php) you cannot really override those patterns in a subclass.

Let's say you have a subclass like this without overriding the `render` function.

    class MyFormRow extends TwbBundleFormRow
    {
        protected static $horizontalLayoutFormat = '<div class="%s" custom-attr="val">%s</div>';
    }

This actually doesn't work at the moment. But it would be very easy to achieve it by changing the calls to those properties like this.

    static::$horizontalLayoutFormat // instead of self::$horizontalLayoutFormat

It matches the PHP requirements (>=5.3) and without them being called with `static` I don't see a reason for those properties to be protected in the first place. This way it would be very nice and easy to subclass the bundle classes because sometimes it's just enough to change those patterns a little bit. Gives you a lot of flexibility.

**Comment by netbrothers-tr** [comment]
For the sake of completeness: One can work around this issue like so.
```
class MyFormRow extends TwbBundleFormRow
{
    public function render(\Zend\Form\ElementInterface $oElement, $sLabelPosition = null)
    {
        self::$horizontalLayoutFormat = '<div class="%s" custom-attr="val">%s</div>';
        return parent::render($oElement, $sLabelPosition);
    }
}
```

**Comment by neilime** [comment]
Hi,

Please can you create a pull request ?

**Comment by netbrothers-tr** [comment]
Thanks @neilime , I will get active about it. I assume I fork the master branch for that matter?

**Comment by neilime** [comment]
PR merged, thank you !
