### ISSUE TITLE
Alias issue

### ISSUE THREAD

**Issue by cbichis** [neilime/zf2-twb-bundle#207]
Hi,

On the last ZF 2 (got one project working on that version) this alias is wrong. It should be removed.

            'Navigation'   => 'TwbBundle\Navigation\View\NavigationHelperFactory',

It throws: An alias "TwbBundle\Navigation\View\NavigationHelperFactory" was requested but no service could be found

**Comment by neilime** [comment]
Can you show the whole stack trace of your error, maybe Zend Navigation is not available in your App due to a missing module

**Comment by cbichis** [comment]
Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: An alias "TwbBundle\Navigation\View\NavigationHelperFactory" was requested but no service could be found. in /www/myproject/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:549 Stack trace: #0 /www/myproject/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(177): Zend\ServiceManager\ServiceManager->get('TwbBundle\\Navig...', true) #1 /www/myproject/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(376): Zend\ServiceManager\AbstractPluginManager->get('navigation', NULL) #2 /www/myproject/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(394): Zend\View\Renderer\PhpRenderer->plugin('navigation') #3 /www/myproject/module/Frontend/view/layout/front3.phtml(113): Zend\View\Renderer\PhpRenderer->__call('navigation', Array) #4 /www/myproject/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/ww...') #5 in /www/myproject/vendor/zendframework/zend-servicemanager/src/Exception/ServiceLocatorUsageException.php on line 34

**Comment by neilime** [comment]
Can you try the last version "v3.3.1"

**Comment by cbichis** [comment]
Thanks, it works. I havent realized I didnt upgraded TWB...
