### ISSUE TITLE
Radios inline in horizontal form

### ISSUE THREAD

**Issue by Paul75** [neilime/zf2-twb-bundle#67]
Hello,

In your example I see :
->add(array(
    'name' => 'optionsRadios',
    'type' => 'MultiCheckbox',
    'options' => array(
        'value_options' => array(
            array('label' => '1','value' => 'option1', 'attributes' => array('id' => 'inlineCheckbox1')),
            array('label' => '2','value' => 'option2', 'attributes' => array('id' => 'inlineCheckbox2')),
            array('label' => '3','value' => 'option3', 'attributes' => array('id' => 'inlineCheckbox3'))
        )
    )
))

It's for Multicheckbox, when I do the same with Radio ? I want to have Radio inline.

Thanks

**Comment by PhUFEB** [comment]
Thanks @sirkohli it helped me. But it affects all labels, how can I get the main label without the class "radio-inline". The "My Radio" label:

```php
$this->add(array(
            'name' => 'my-radio',
            'type' => 'Radio',
            'options' => array(
                'label' => 'My Radio',
                'value_options' => array(
                    1 => '#1',
                    2 => '#2,
                ),
                'disable-twb' => true,
                'label_attributes' => array(
                    'class' => 'radio-inline'
                ),
            ),
        ));
```
